server:
  port: 8001
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
spring:
  application:
    name: service-client
  zipkin:
    base-url: http://localhost:2000