server:
  port: 8005
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
spring:
  application:
    name: service-feign
feign:
  hystrix:
    enabled: true
  compression:
    request:
      mime-types:
