#server:
#  port: 8011
#spring:
#  zipkin:
#    base-url: http://localhost:2000
#  application:
#    name: service-hi

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-hi
